---
title: "cervunales"
author: "Estefania&Marcial"
date: "03/15/2018"
output: html_document
---
1. Install and load packages

```{r}
#install.packages("picante")
#This will install also package dependences
library(picante)
#This will also load package dependences
#library(ape)
#library(vegan)
#library(permute)
#library(lattice)
#library(nlme)


```

2. Open your tree, edit and plot

```{r}
mytree <- read.tree("cervunales.dated.tree")
mytree
plot(mytree)
plot(mytree, cex = 0.5)
mytree <- drop.tip(mytree, "Genista_anglica")
plot(mytree, cex = 0.5)

```


3. Frequency matrix.

```{r}
mydata <- read.csv("mydata.csv", sep = ",")
mydata
rownames(mydata) = mydata[,1]
setdiff(mydata[,1], mytree$tip.label)
setdiff(mytree$tip.label,mydata[,1])

```

4. Calculate phylogenetic diversity statistics.

```{r}
color.plot.phylo(mytree, mydata, "GRNA_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Gredos Norte Alto") 
color.plot.phylo(mytree, mydata, "GRNB_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Gredos Norte Bajo") 
color.plot.phylo(mytree, mydata, "GRSA_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Gredos Sur Alto") 
color.plot.phylo(mytree, mydata, "GRSB_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Gredos Sur Bajo") 
color.plot.phylo(mytree, mydata, "SNNA_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Sierra Nevada Norte Alto") 
color.plot.phylo(mytree, mydata, "SNNB_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Sierra Nevada Norte Bajo") 
color.plot.phylo(mytree, mydata, "SNSA_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Sierra Nevada Sur Alto") 
color.plot.phylo(mytree, mydata, "SNSB_frec_prom", "Especie_epiteto", leg.cex = 0.6, main = "Sierra Nevada Sur Bajo") 

mypd <- pd(t(mydata[,-c(1,2)]), mytree, include.root=TRUE)
mypd

mympd <- mpd(t(mydata[,-c(1,2)]), cophenetic(mytree), abundance.weighted=T)
mympd
myresults1 <- cbind(mypd, mympd)

mymntd <- mntd(t(mydata[,-c(1,2)]), cophenetic(mytree), abundance.weighted=T)
mymntd
myresults2 <- cbind(myresults1, mymntd)
colnames(myresults2) <- c("PD", "SR", "MPD", "MNTD")
write.table(myresults2, file = "diversity_index_results.txt")

mycomdist <- comdist(t(mydata[,-c(1,2)]), cophenetic(mytree), abundance.weighted=T)
library(cluster)
mycomdist.clusters <- hclust(mycomdist)
plot(mycomdist.clusters, main = "Dendrogram based on beta MPD")

mycomdistnt1 <- comdistnt(t(mydata[,-c(1,2)]), cophenetic(mytree), abundance.weighted=F, exclude.conspecifics = T)
mycomdistnt1.clusters <- hclust(mycomdistnt1)
plot(mycomdistnt1.clusters, main = "Dendrogram based on beta MNTD excluding conspecifics")

mycomdistnt2 <- comdistnt(t(mydata[,-c(1,2)]), cophenetic(mytree), abundance.weighted=F, exclude.conspecifics = F)
mycomdistnt2.clusters <- hclust(mycomdistnt2)
plot(mycomdistnt2.clusters, main = "Dendrogram based on beta MNTD including conspecifics")

my.ses.pd <- ses.pd(t(mydata[,-c(1,2)]), mytree, null.model = "taxa.labels",
runs = 999)
my.ses.pd
write.table(my.ses.pd, file="ses.pd.result.txt")

my.ses.mpd <- ses.mpd(t(mydata[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mpd
write.table(my.ses.mpd, file="ses.mpd.result.txt")


my.ses.mntd <- ses.mntd(t(mydata[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mntd
write.table(my.ses.mntd, file="ses.mntd.result.txt")



comm.phylo.cor.r <- comm.phylo.cor(t(mydata[,-c(1,2)]), mytree, metric="cij",null.model="sample.taxa.labels")
comm.phylo.cor.r
par(mai=c(1.02,0.82,0.82,0.42))
hist(comm.phylo.cor.r$random.corrs)
abline(v=comm.phylo.cor.r$obs.corr)

```

5. Loading data set Gredos vs. Sierra Nevada

```{r}

mydata2 <- read.csv("mydata2.csv", sep = ",")
mydata2
rownames(mydata2) = mydata2[,1]
setdiff(mydata2[,1], mytree$tip.label)
setdiff(mytree$tip.label,mydata2[,1])

```
6. Calculate phylogenetic diversity statistics.

```{r}
color.plot.phylo(mytree, mydata2, "GR", "Especie_epiteto", leg.cex = 0.6, main = "Gredos") 
color.plot.phylo(mytree, mydata2, "SN", "Especie_epiteto", leg.cex = 0.6, main = "Sierra Nevada") 

mypd2 <- pd(t(mydata2[,-c(1,2)]), mytree, include.root=TRUE)
mypd2

mympd2 <- mpd(t(mydata2[,-c(1,2)]), cophenetic(mytree), abundance.weighted=T)
mympd2
myresults12 <- cbind(mypd2, mympd2)

mymntd2 <- mntd(t(mydata2[,-c(1,2)]), cophenetic(mytree), abundance.weighted=T)
mymntd2
myresults22 <- cbind(myresults12, mymntd2)
colnames(myresults22) <- c("PD", "SR", "MPD", "MNTD")
write.table(myresults22, file = "diversity_index_results_GRvsSN.txt")

my.ses.pd2 <- ses.pd(t(mydata2[,-c(1,2)]), mytree, null.model = "taxa.labels",
runs = 999)
my.ses.pd2
write.table(my.ses.pd2, file="ses.pd.result.GRvsSN.txt")

my.ses.mpd2 <- ses.mpd(t(mydata2[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mpd2
write.table(my.ses.mpd2, file="ses.mpd.result.GRvsSN.txt")


my.ses.mntd2 <- ses.mntd(t(mydata2[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mntd2
write.table(my.ses.mntd2, file="ses.mntd.result.GRvsSN.txt")



comm.phylo.cor.r2 <- comm.phylo.cor(t(mydata2[,-c(1,2)]), mytree, metric="cij",null.model="sample.taxa.labels")
comm.phylo.cor.r2
par(mai=c(1.02,0.82,0.82,0.42))
hist(comm.phylo.cor.r2$random.corrs)
abline(v=comm.phylo.cor.r2$obs.corr)

```


